language:
  ruby
rvm:
  - '2.4.1'
script:
  bundle exec rspec spec/*.rb
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y cloc gdal-bin gdebi-core libcurl4-openssl-dev lingdal-dev libproj-dev libxml2.dev build-essential libmysqlclient-dev libsqlite3-dev
